language: bash

sudo: required
services:
  - docker

before_script:
  - docker pull mongo:4
  - docker-compose -f docker-compose.testing.yml up -d --build

script: >-
  docker ps -a &&
  docker logs -f $(docker ps -a -q --filter="name=caronte_caronte") | grep "travis" |
    (read status; if [[ $status == "travis_tests_fails" ]]; then exit 1; fi)

after_success:
  - docker cp "$(docker ps -a -q --filter='name=caronte_caronte'):/caronte/coverage.txt" coverage.txt
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - docker logs $(docker ps -a -q --filter="name=caronte_caronte")
  - docker-compose -f docker-compose.testing.yml down
