version: "3.7"
services:

  mongo:
    image: mongo:4
    networks:
      - acheronet
    restart: always

  caronte:
    image: eciavatta/caronte:latest
    ports:
      - "3333:3333"
    depends_on:
      - mongo
    networks:
      - acheronet
    command: ./caronte -mongo-host mongo -mongo-port 27017

networks:
  acheronet:
