version: "3.7"
services:

  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
    networks:
      - acheronet
    restart: always

  caronte:
    image: caronte
    ports:
      - "3333:3333"
    depends_on:
      - mongo
    networks:
      - acheronet
    command: ./caronte -mongo-host mongo -mongo-port 27017 -assembly_memuse_log

networks:
  acheronet:
