version: "3.7"
services:

  mongo:
    image: mongo:4.4

  test:
    build:
      context: ../../
      dockerfile: .github/docker/Dockerfile
    image: caronte-test
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
